#!/bin/bash echo "ALX"
#!/bin/bash echo "School"
#!/bin/bash echo "ALX"
#!/bin/bash echo "School"
#!/bin/bash echo "ALX"
#!/bin/bash "ALX"
#!/bin/bash echo "ALX"
#!/bin/bash echo "School"
#!/bin/bash
"ALX"
#!/bin/bash
"School"
